# Ventorystack: Docker Compose
# https://docs.docker.com/compose/
#
# Usage: test up
version: '3'
services:

  # PostgreSQL database
  db_test:
    restart: always
    image: dgnest/postgres:9.6
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=golang_test
    env_file:
      - .env
    volumes:
      - pgvolume-9.6-test:/var/lib/postgresql/data #using the declared volume

  # Django web server
  web:
    environment: &environment
      - DB_URL=postgres://postgres:postgres@db:5432/golang
      - DB_TEST_URL=postgres://postgres:postgres@db_test:5432/golang_test
    depends_on:
      - db_test

volumes:
  pgvolume-coursego-9.6-test:
    external:
      name: pgvolume-coursego-9-6-test
